### ISSUE TITLE
Add field how to enable the TATE/vertical mode

### ISSUE THREAD

**Issue by silverhook** [Alshie/does-it-flip#4]
Different games have different ways how to enable their TATE or vertical orientation. It would be good to gather the info on how to do that – either in `additional_info`, or better yet, in a separate dedicated field.

If you implement that, I volunteer to add the info for the games I have.

**Comment by Alshie** [comment]
I think this is worth doing - dedicated field is probably better.

I'll look into getting this on the site asap - if you want to update any you know of in the interim period that would be great. I will add any I have also & put a call out for help.

 Maybe call the field `instructions` ?

**Comment by Alshie** [comment]
Thank you again!

**Comment by silverhook** [comment]
`instructions` sounds good to me, yes :)

Once you have it, feel free to ping me and I’ll add what I know.

**Comment by silverhook** [comment]
Ping, @Alshie ? :)

**Comment by Alshie** [comment]
Thanks for reminding me about this. I have some plans for changing the whole setup but I've been really busy with day job and this had slipped down my list.

However - rather than sitting on longer, I've added and `instructions` field and included it on each gams card where if it exists. I've gone through and added all the ones that I have currently, any more would be appreciated!

Special shout out to Hamster who seem to have 4 different ways of enabling TATE mode across the Arcade Archives series! 😃

**Comment by Alshie** [comment]
May need to hard refresh the site a few times to see the new fields, I think the service worker is caching everything a little too aggressively, need to look into it.

**Comment by silverhook** [comment]
Sweet! I’ll add the few that I have and you haven’t added yet.

**Comment by silverhook** [comment]
Added a few in https://github.com/Alshie/does-it-flip/pull/8

Also, closing this issue, as it has been resolved :+1:
